version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: "see items"
          command: |
            ls -all
            pwd
      - run:
          name: "copy app"
          command: |
            scp ./target/demo-0.0.1-SNAPSHOT.jar ubuntu@3.15.185.131:~
  # copy-file:  
  #   docker:
  #     - image: cimg/base:2021.04 
  #   steps:
  #     - checkout
      
      

workflows:
  sample: 
    jobs:
      - build-and-test
      # - copy-file:
      #     requires:
      #       - build-and-test
      #     filters:
      #       branches:
      #         only: dev
      
