version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  build-and-test-dev:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - persist_to_workspace:
          root: /home/circleci/project/target
          paths:
            - demo.war
  deploy-app-dev:
    executor: my-executor
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "91:d8:12:a6:9c:c5:11:d2:9d:42:15:9e:d0:e0:87:b5"
      - run:
          name: "stop last app"
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@${ipServer1} "./apache-tomcat-9.0.46/bin/shutdown.sh"
      - run:
          name: "copy app"
          command: |
            scp -o StrictHostKeyChecking=no ./demo.war ubuntu@${ipServer1}:~/apache-tomcat-9.0.46/webapps/demo.war
      - run:
          name: "run app"
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@${ipServer1} "./apache-tomcat-9.0.46/bin/startup.sh"

workflows:
  dev:
    jobs:
      - build-and-test-dev:
          filters:
            branches:
              only:
                - dev
      - hold-dev:
          type: approval
          requires:
            - build-and-test-dev
      - deploy-app-dev:
          requires:
            - hold-dev
