version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: "see items"
          command: |
            cd ..
            cd .ssh
            ls -all
      - add_ssh_keys:
          fingerprints:
            - "91:d8:12:a6:9c:c5:11:d2:9d:42:15:9e:d0:e0:87:b5"
      - run:
          name: "stop last app"
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.15.185.131 "sudo pkill -f 'java -jar'"
      - run:
          name: "copy app"
          command: |
            scp -oStrictHostKeyChecking=no ./target/demo-0.0.1-SNAPSHOT.jar ubuntu@3.15.185.131:~
      - run:
          name: "run app"
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@3.15.185.131 "java -jar ./demo-0.0.1-SNAPSHOT.jar & echo 1"
  # copy-file:  
  #   docker:
  #     - image: cimg/base:2021.04 
  #   steps:
  #     - checkout
      
      

workflows:
  sample: 
    jobs:
      - build-and-test
      # - copy-file:
      #     requires:
      #       - build-and-test
      #     filters:
      #       branches:
      #         only: dev
      
